<?php

namespace Mintreu\LaravelForm;

use Livewire\Livewire;
use Mintreu\LaravelForm\Http\Livewire\Field\Select;
use Mintreu\LaravelForm\Http\Livewire\Field\TextInput;
use Mintreu\LaravelForm\Http\Livewire\Form;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Mintreu\LaravelForm\Commands\LaravelFormCommand;

class LaravelFormServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('laravel-form')
            ->hasConfigFile()
            ->hasViews()
            ->hasMigration('create_laravel-form_table')
            ->hasCommand(LaravelFormCommand::class);
    }


    public function bootingPackage()
    {
        Livewire::component('form::form',Form::class);
        Livewire::component('form::field.text-input',TextInput::class);
        Livewire::component('form::field.select',Select::class);

        parent::bootingPackage(); // TODO: Change the autogenerated stub
    }


}
